name: nightly-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: model test
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install .
        pip install pytest onnxruntime
        python tests/test_folder.py --model-dir /root/data/modelzoo
