name: nightly-test

on:
  schedule:
    - cron: "0 18 * * *" # Runs at 6:00 PM UTC every day, which is 2:00 AM Beijing Time the next day
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: "3.12"

      - name: install dependency
        run: uv sync --dev

      - name: benchmark test
        run: uv run python tests/test_benchmark.py

  timm-test:
    runs-on: self-hosted
    needs: benchmark

    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: "3.12"

      - name: install dependency
        run: uv sync --dev --group model-tests

      - name: timm test
        run: uv run python tests/test_onnx_nets.py

  ultralytics-test:
    runs-on: self-hosted
    needs: timm-test

    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: "3.12"

      - name: install dependency
        run: uv sync --dev --group ultralytics

      - name: ultralytics test
        run: uv run pytest tests/test_ultralytics.py -v -n 1

  optimum-test:
    runs-on: self-hosted
    needs: ultralytics-test

    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: "3.12"

      - name: install dependency
        run: uv sync --dev --group optimum

      - name: optimum test
        run: uv run pytest tests/exporters/onnx/test_export_cli.py -v -n 4
